rova: audio: fix validation errors
Error: Element 'profile', attribute 'channelMasks': [facet 'pattern'] The value 'dynamic' is not accepted by the pattern '[_A-Z][_A-Z0-9]*(,[_A-Z][_A-Z0-9]*)*'.
Error: Element 'route': Duplicate key-sequence ['Telephony Tx'] in unique identity-constraint 'routeUniqueness'.

[cafebabe] Removal of channelMasks="dynamic" has already done by commit "Remove dynamic attributes from APS config"

Issue: FP3-A12#24
Change-Id: I76a5debb1e5e80d3563166616b489d83a0f49c9a